[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/solana-labs/ntapi?rev=97ede981a1777883ff86d142b75024b023f04fad"]
git = "https://github.com/solana-labs/ntapi"
rev = "97ede981a1777883ff86d142b75024b023f04fad"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
